"""Pipeline Ingestion Service for Scraped Flight/Fare Payloads.

Bridges raw and normalized scraper outputs (such as JSON files generated by
``cleartrip_ui.py`` in ``data/normalized/cleartrip/``) into the core SIH 26056
pipeline:

    Scraper / Normalized JSON
                ↓
    Payload Extractor & Raw Record Builder
                ↓
    Common Pipeline: Validation → Cleaning → Normalization → Deduplication
                ↓
    PostgreSQL Database Persistence (fares table, ON CONFLICT DO NOTHING)
                ↓
    Index Engine Recalculation (PSD weights, Laspeyres, Jevons)
                ↓
    Cache Invalidation (Real-time update across FastAPI & Web Dashboard)
"""

from __future__ import annotations

import argparse
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from database.connection import get_connection
from database.repository import (
    get_fares,
    insert_fares,
    insert_index_result,
    invalidate_fares_cache,
    invalidate_index_cache,
)
from index_engine.aggregation import aggregate_item_price_relatives
from index_engine.api_index import compute_overall_airfare_index
from index_engine.weights import compute_psd_base_basket_weights
from models.fare import Fare
from pipeline import process_raw_fares
from scraper.otas.cleartrip_live import flight_to_raw_records

logger = logging.getLogger("pipeline.ingest")


def invalidate_all_caches() -> None:
    """Invalidate all in-memory repository and dashboard caches."""
    invalidate_fares_cache()
    invalidate_index_cache()

    try:
        from dashboard.components import invalidate_kpi_cache
        invalidate_kpi_cache()
    except Exception as exc:
        logger.debug("KPI cache invalidation skipped: %s", exc)

    try:
        from dashboard.blueprint_service import invalidate_blueprint_cache
        invalidate_blueprint_cache()
    except Exception as exc:
        logger.debug("Blueprint cache invalidation skipped: %s", exc)

    try:
        import dashboard.app as d_app
        d_app._CHARTS_CACHE = None
        d_app._HEATMAP_CACHE = None
    except Exception as exc:
        logger.debug("Dashboard charts cache invalidation skipped: %s", exc)


def list_normalized_files(
    base_dir: Union[str, Path] = "data/normalized",
) -> List[Dict[str, Any]]:
    """Scan and list available normalized scrape JSON files."""
    path = Path(base_dir)
    if not path.exists():
        return []

    results: List[Dict[str, Any]] = []
    for file_path in sorted(path.rglob("*.json"), reverse=True):
        try:
            stat = file_path.stat()
            file_info: Dict[str, Any] = {
                "file_name": file_path.name,
                "file_path": str(file_path),
                "size_kb": round(stat.st_size / 1024, 2),
                "modified_at": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
            }

            # Quick peek at payload metadata without loading entire file if large
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    preview = json.load(f)
                if isinstance(preview, dict):
                    file_info["source"] = preview.get("source", "unknown")
                    file_info["route"] = preview.get("route", {})
                    file_info["departure_date"] = preview.get("departure_date")
                    file_info["flight_count"] = preview.get("flight_count", len(preview.get("flights", [])))
            except Exception:
                pass

            results.append(file_info)
        except Exception as exc:
            logger.warning("Error reading file %s: %s", file_path, exc)

    return results


def _build_source_url(payload: Dict[str, Any], candidate_url: Optional[str] = None) -> Optional[str]:
    """Return a strictly valid HTTP/HTTPS URL for provenance or None."""
    if candidate_url and candidate_url.startswith(("http://", "https://")):
        return candidate_url

    route = payload.get("route", {})
    orig = route.get("origin", "")
    dest = route.get("destination", "")
    if orig and dest:
        return f"https://www.cleartrip.com/flights/results?from={orig}&to={dest}"
    return "https://www.cleartrip.com/flights"


def parse_normalized_payload(
    payload: Union[Dict[str, Any], List[Dict[str, Any]]],
    source_url: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Convert normalized scrape JSON into common raw fare observation dictionaries.

    Supports:
    1. Cleartrip normalized object: ``{"source": "cleartrip", "flights": [...]}``
    2. List of normalized flight objects: ``[{"airline_code": "IX", ...}]``
    3. Already converted raw fare records: ``[{"airline_code": "IX", "price_inr": ...}]``
    """
    raw_records: List[Dict[str, Any]] = []

    if isinstance(payload, dict):
        flights = payload.get("flights", [])
        scraped_stamp_str = payload.get("captured_at_utc")
        valid_url = _build_source_url(payload, source_url)

        scraped_dt = None
        if scraped_stamp_str:
            try:
                scraped_dt = datetime.strptime(scraped_stamp_str, "%Y%m%dT%H%M%SZ").replace(tzinfo=timezone.utc)
            except Exception:
                scraped_dt = datetime.now(timezone.utc)

        for flight in flights:
            records = flight_to_raw_records(
                flight=flight,
                scraped_at=scraped_dt,
                source_url=valid_url,
            )
            raw_records.extend(records)

    elif isinstance(payload, list):
        for item in payload:
            if not isinstance(item, dict):
                continue
            if "fares" in item and "departure" in item:
                # Flight object
                records = flight_to_raw_records(flight=item, source_url="https://www.cleartrip.com/flights")
                raw_records.extend(records)
            elif "price_inr" in item and "airline_code" in item:
                # Already raw fare record
                raw_records.append(item)

    return raw_records


def recompute_indices_for_fares(
    conn: Any,
    fares: List[Fare],
) -> int:
    """Recompute and persist APIx index records for all dates present in the new fares."""
    if not fares:
        return 0

    all_stored_fares = get_fares(conn)
    target_dates = sorted({f.scraped_at.date() for f in fares})

    indices_created = 0
    for d in target_dates:
        try:
            relatives = aggregate_item_price_relatives(all_stored_fares, current_period=d)
            weights = compute_psd_base_basket_weights(relatives.item_price_relatives)
            index_res = compute_overall_airfare_index(relatives, weights)
            insert_index_result(conn, index_res)
            indices_created += 1
        except Exception as exc:
            logger.warning("Could not compute/persist APIx index for period %s: %s", d, exc)

    return indices_created


def ingest_normalized_file(
    file_path: Union[str, Path],
    conn: Any = None,
    recompute_index: bool = True,
) -> Dict[str, Any]:
    """Process and ingest a single normalized scrape JSON file into the database.

    Chains:
    1. Read JSON file
    2. Extract raw fare records
    3. Common pipeline (validate_batch -> clean -> normalize -> dedup)
    4. Database insertion into PostgreSQL (fares table)
    5. APIx index recomputation
    6. Complete cache invalidation
    """
    path = Path(file_path)
    if not path.is_file():
        raise FileNotFoundError(f"Normalized scrape file not found: {path}")

    with open(path, "r", encoding="utf-8") as f:
        payload = json.load(f)

    raw_records = parse_normalized_payload(payload)
    if not raw_records:
        return {
            "status": "empty",
            "file": str(path),
            "message": "No flight fare observations found in payload",
            "raw_records_count": 0,
            "valid_fares": 0,
            "rejected_fares": 0,
            "new_fares_inserted": 0,
            "indices_updated": 0,
        }

    # Pass through standard pipeline
    fares, bad_records, batch_error = process_raw_fares(raw_records)
    if batch_error is not None:
        return {
            "status": "batch_validation_error",
            "file": str(path),
            "message": str(batch_error),
            "raw_records_count": len(raw_records),
            "valid_fares": 0,
            "rejected_fares": len(bad_records),
            "new_fares_inserted": 0,
            "indices_updated": 0,
        }

    # Persist to database
    db_conn = conn or get_connection()
    inserted_count = insert_fares(db_conn, fares)

    # Recalculate index if requested
    indices_updated = 0
    if recompute_index and fares:
        indices_updated = recompute_indices_for_fares(db_conn, fares)

    # Invalidate all caches so dashboard and APIs immediately pick up the new data
    invalidate_all_caches()

    return {
        "status": "success",
        "file": str(path),
        "source": payload.get("source") if isinstance(payload, dict) else "unknown",
        "route": payload.get("route") if isinstance(payload, dict) else None,
        "departure_date": payload.get("departure_date") if isinstance(payload, dict) else None,
        "raw_records_count": len(raw_records),
        "valid_fares": len(fares),
        "rejected_fares": len(bad_records),
        "new_fares_inserted": inserted_count,
        "indices_updated": indices_updated,
    }


def ingest_normalized_directory(
    dir_path: Union[str, Path] = "data/normalized/cleartrip",
    conn: Any = None,
    recompute_index: bool = True,
) -> Dict[str, Any]:
    """Ingest all normalized scrape JSON files in a directory."""
    path = Path(dir_path)
    if not path.is_dir():
        return {
            "status": "directory_not_found",
            "directory": str(path),
            "files_processed": 0,
            "total_valid_fares": 0,
            "total_inserted": 0,
            "details": [],
        }

    files = sorted(path.glob("*.json"))
    db_conn = conn or get_connection()

    total_valid = 0
    total_inserted = 0
    details = []

    for f in files:
        try:
            res = ingest_normalized_file(f, conn=db_conn, recompute_index=False)
            total_valid += res.get("valid_fares", 0)
            total_inserted += res.get("new_fares_inserted", 0)
            details.append(res)
        except Exception as exc:
            details.append({"file": str(f), "status": "error", "error": str(exc)})

    # Recompute indices once across all newly inserted fares
    indices_updated = 0
    if recompute_index and total_inserted > 0:
        all_fares = get_fares(db_conn)
        indices_updated = recompute_indices_for_fares(db_conn, all_fares[-100:])

    invalidate_all_caches()

    return {
        "status": "success",
        "directory": str(path),
        "files_processed": len(files),
        "total_valid_fares": total_valid,
        "total_inserted": total_inserted,
        "indices_updated": indices_updated,
        "details": details,
    }


def main() -> int:
    """CLI entry point for pipeline ingestion."""
    parser = argparse.ArgumentParser(
        description="Ingest normalized flight fare JSON files into the SIH 26056 database."
    )
    parser.add_argument(
        "--file",
        dest="file_path",
        help="Path to a single normalized JSON file (e.g. data/normalized/cleartrip/cleartrip_flights_....json)",
    )
    parser.add_argument(
        "--dir",
        dest="dir_path",
        default="data/normalized/cleartrip",
        help="Directory containing normalized JSON files (default: data/normalized/cleartrip)",
    )
    parser.add_argument(
        "--no-recompute-index",
        action="store_true",
        help="Skip APIx index recomputation after ingestion",
    )

    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

    print("=" * 60)
    print("SIH 26056: SCRAPED FARE PIPELINE INGESTION")
    print("=" * 60)

    recompute = not args.no_recompute_index

    if args.file_path:
        print(f"Ingesting single file: {args.file_path}")
        result = ingest_normalized_file(args.file_path, recompute_index=recompute)
    else:
        print(f"Scanning directory for normalized files: {args.dir_path}")
        result = ingest_normalized_directory(args.dir_path, recompute_index=recompute)

    print("\n[INGESTION RESULT]")
    print(json.dumps(result, indent=2))
    print("=" * 60)
    print("✓ Data successfully ingested, validated, persisted, and synced to dashboard!")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
