"""Search job and request contracts for the acquisition pipeline.

This module defines SearchJob (dataclass) and
SearchRequest (Pydantic model) for scheduler
orchestration. These classes represent a single acquisition request with all
necessary parameters for flight scrapers (e.g. Cleartrip live scrape).

The contract matches the specification:
- source: "cleartrip"
- origin/destination IATA codes
- departure_date (ISO YYYY-MM-DD or DD/MM/YYYY)
- optional return_date
- passenger counts (adults, children, infants)
- cabin class (ECONOMY/PREMIUM_ECONOMY/BUSINESS/FIRST)
- trip_type (ONE_WAY/ROUND_TRIP)
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

from models.route import Route

__all__ = ["SearchJob", "SearchRequest"]


def _format_date_cleartrip(value: str) -> str:
    """Accept DD/MM/YYYY or YYYY-MM-DD and return DD/MM/YYYY."""
    s = value.strip()
    for fmt in ("%d/%m/%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(s, fmt).strftime("%d/%m/%Y")
        except ValueError:
            pass
    raise ValueError(
        f"Invalid date format '{value}', expected YYYY-MM-DD or DD/MM/YYYY"
    )


def _format_date_iso(value: str) -> str:
    """Accept DD/MM/YYYY or YYYY-MM-DD and return YYYY-MM-DD."""
    s = value.strip()
    for fmt in ("%Y-%m-%d", "%d/%m/%Y"):
        try:
            return datetime.strptime(s, fmt).strftime("%Y-%m-%d")
        except ValueError:
            pass
    raise ValueError(
        f"Invalid date format '{value}', expected YYYY-MM-DD or DD/MM/YYYY"
    )


@dataclass(slots=True)
class SearchJob:
    """Represents a single acquisition request generated by the scheduler.

    All parameters are parameterized rather than hardcoded.
    """

    source: str
    origin: str
    destination: str
    departure_date: str
    return_date: Optional[str] = None
    adults: int = 1
    children: int = 0
    infants: int = 0
    cabin: str = "ECONOMY"
    trip_type: str = "ONE_WAY"

    def __post_init__(self) -> None:
        object.__setattr__(self, "origin", self.origin.strip().upper())
        object.__setattr__(self, "destination", self.destination.strip().upper())
        object.__setattr__(self, "cabin", self.cabin.strip().upper())
        object.__setattr__(self, "trip_type", self.trip_type.strip().upper())

    @property
    def cleartrip_date(self) -> str:
        """Departure date in DD/MM/YYYY format required by Cleartrip."""
        return _format_date_cleartrip(self.departure_date)

    @property
    def iso_date(self) -> str:
        """Departure date in canonical ISO YYYY-MM-DD format."""
        return _format_date_iso(self.departure_date)

    def to_route(self) -> Route:
        """Convert origin/destination to canonical Route domain model."""
        return Route(origin=self.origin, destination=self.destination)

    def key(self) -> tuple:
        """Deterministic key for deduplication and scheduling."""
        return (
            self.source.lower(),
            self.origin,
            self.destination,
            self.iso_date,
            self.return_date or "",
            self.adults,
            self.children,
            self.infants,
            self.cabin,
            self.trip_type,
        )


class SearchRequest(BaseModel):
    """Convenience builder for SearchJob creation with Pydantic validation."""

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
    )

    source: str = Field(..., min_length=1)
    origin: str = Field(..., min_length=3, max_length=3)
    destination: str = Field(..., min_length=3, max_length=3)
    departure_date: str = Field(..., description="ISO date YYYY-MM-DD or DD/MM/YYYY")
    return_date: Optional[str] = None
    adults: int = Field(default=1, ge=0)
    children: int = Field(default=0, ge=0)
    infants: int = Field(default=0, ge=0)
    cabin: str = Field(
        default="ECONOMY", pattern="^(ECONOMY|PREMIUM_ECONOMY|BUSINESS|FIRST)$"
    )
    trip_type: str = Field(default="ONE_WAY", pattern="^(ONE_WAY|ROUND_TRIP)$")

    @field_validator("origin", "destination", mode="before")
    @classmethod
    def _normalize_codes(cls, v: str) -> str:
        return str(v).strip().upper()

    def to_job(self) -> SearchJob:
        """Convert to a SearchJob instance."""
        return SearchJob(
            source=self.source,
            origin=self.origin,
            destination=self.destination,
            departure_date=self.departure_date,
            return_date=self.return_date,
            adults=self.adults,
            children=self.children,
            infants=self.infants,
            cabin=self.cabin,
            trip_type=self.trip_type,
        )
